// Generated by gencpp from file eve_msgs/Brake.msg
// DO NOT EDIT!


#ifndef EVE_MSGS_MESSAGE_BRAKE_H
#define EVE_MSGS_MESSAGE_BRAKE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace eve_msgs
{
template <class ContainerAllocator>
struct Brake_
{
  typedef Brake_<ContainerAllocator> Type;

  Brake_()
    : header()
    , percentage(0)  {
    }
  Brake_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , percentage(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _percentage_type;
  _percentage_type percentage;





  typedef boost::shared_ptr< ::eve_msgs::Brake_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::eve_msgs::Brake_<ContainerAllocator> const> ConstPtr;

}; // struct Brake_

typedef ::eve_msgs::Brake_<std::allocator<void> > Brake;

typedef boost::shared_ptr< ::eve_msgs::Brake > BrakePtr;
typedef boost::shared_ptr< ::eve_msgs::Brake const> BrakeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::eve_msgs::Brake_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::eve_msgs::Brake_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::eve_msgs::Brake_<ContainerAllocator1> & lhs, const ::eve_msgs::Brake_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.percentage == rhs.percentage;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::eve_msgs::Brake_<ContainerAllocator1> & lhs, const ::eve_msgs::Brake_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace eve_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::eve_msgs::Brake_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::eve_msgs::Brake_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eve_msgs::Brake_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eve_msgs::Brake_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eve_msgs::Brake_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eve_msgs::Brake_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::eve_msgs::Brake_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cef99679ab537b09bc625498c4d83b23";
  }

  static const char* value(const ::eve_msgs::Brake_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcef99679ab537b09ULL;
  static const uint64_t static_value2 = 0xbc625498c4d83b23ULL;
};

template<class ContainerAllocator>
struct DataType< ::eve_msgs::Brake_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eve_msgs/Brake";
  }

  static const char* value(const ::eve_msgs::Brake_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::eve_msgs::Brake_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"# Range 0 to 100, 100 is max brake\n"
"int8 percentage\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::eve_msgs::Brake_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::eve_msgs::Brake_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.percentage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Brake_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::eve_msgs::Brake_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::eve_msgs::Brake_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "percentage: ";
    Printer<int8_t>::stream(s, indent + "  ", v.percentage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EVE_MSGS_MESSAGE_BRAKE_H
