// Generated by gencpp from file eve_msgs/GearRequest.msg
// DO NOT EDIT!


#ifndef EVE_MSGS_MESSAGE_GEARREQUEST_H
#define EVE_MSGS_MESSAGE_GEARREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace eve_msgs
{
template <class ContainerAllocator>
struct GearRequest_
{
  typedef GearRequest_<ContainerAllocator> Type;

  GearRequest_()
    : mode(0)  {
    }
  GearRequest_(const ContainerAllocator& _alloc)
    : mode(0)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::eve_msgs::GearRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::eve_msgs::GearRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GearRequest_

typedef ::eve_msgs::GearRequest_<std::allocator<void> > GearRequest;

typedef boost::shared_ptr< ::eve_msgs::GearRequest > GearRequestPtr;
typedef boost::shared_ptr< ::eve_msgs::GearRequest const> GearRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::eve_msgs::GearRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::eve_msgs::GearRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::eve_msgs::GearRequest_<ContainerAllocator1> & lhs, const ::eve_msgs::GearRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::eve_msgs::GearRequest_<ContainerAllocator1> & lhs, const ::eve_msgs::GearRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace eve_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::eve_msgs::GearRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::eve_msgs::GearRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eve_msgs::GearRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eve_msgs::GearRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eve_msgs::GearRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eve_msgs::GearRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::eve_msgs::GearRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89b81386720be1cd0ce7a3953fcd1b19";
  }

  static const char* value(const ::eve_msgs::GearRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89b81386720be1cdULL;
  static const uint64_t static_value2 = 0x0ce7a3953fcd1b19ULL;
};

template<class ContainerAllocator>
struct DataType< ::eve_msgs::GearRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eve_msgs/GearRequest";
  }

  static const char* value(const ::eve_msgs::GearRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::eve_msgs::GearRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 0	REVERSE\n"
"# 1	NEUTRAL\n"
"# 2	FORWARD\n"
"# 3	BOOST\n"
"\n"
"uint8 mode\n"
;
  }

  static const char* value(const ::eve_msgs::GearRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::eve_msgs::GearRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GearRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::eve_msgs::GearRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::eve_msgs::GearRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EVE_MSGS_MESSAGE_GEARREQUEST_H
