// Generated by gencpp from file eve_msgs/Headlight.msg
// DO NOT EDIT!


#ifndef EVE_MSGS_MESSAGE_HEADLIGHT_H
#define EVE_MSGS_MESSAGE_HEADLIGHT_H

#include <ros/service_traits.h>


#include <eve_msgs/HeadlightRequest.h>
#include <eve_msgs/HeadlightResponse.h>


namespace eve_msgs
{

struct Headlight
{

typedef HeadlightRequest Request;
typedef HeadlightResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Headlight
} // namespace eve_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::eve_msgs::Headlight > {
  static const char* value()
  {
    return "800f34bc468def1d86e2d42bea5648c0";
  }

  static const char* value(const ::eve_msgs::Headlight&) { return value(); }
};

template<>
struct DataType< ::eve_msgs::Headlight > {
  static const char* value()
  {
    return "eve_msgs/Headlight";
  }

  static const char* value(const ::eve_msgs::Headlight&) { return value(); }
};


// service_traits::MD5Sum< ::eve_msgs::HeadlightRequest> should match
// service_traits::MD5Sum< ::eve_msgs::Headlight >
template<>
struct MD5Sum< ::eve_msgs::HeadlightRequest>
{
  static const char* value()
  {
    return MD5Sum< ::eve_msgs::Headlight >::value();
  }
  static const char* value(const ::eve_msgs::HeadlightRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::eve_msgs::HeadlightRequest> should match
// service_traits::DataType< ::eve_msgs::Headlight >
template<>
struct DataType< ::eve_msgs::HeadlightRequest>
{
  static const char* value()
  {
    return DataType< ::eve_msgs::Headlight >::value();
  }
  static const char* value(const ::eve_msgs::HeadlightRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::eve_msgs::HeadlightResponse> should match
// service_traits::MD5Sum< ::eve_msgs::Headlight >
template<>
struct MD5Sum< ::eve_msgs::HeadlightResponse>
{
  static const char* value()
  {
    return MD5Sum< ::eve_msgs::Headlight >::value();
  }
  static const char* value(const ::eve_msgs::HeadlightResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::eve_msgs::HeadlightResponse> should match
// service_traits::DataType< ::eve_msgs::Headlight >
template<>
struct DataType< ::eve_msgs::HeadlightResponse>
{
  static const char* value()
  {
    return DataType< ::eve_msgs::Headlight >::value();
  }
  static const char* value(const ::eve_msgs::HeadlightResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EVE_MSGS_MESSAGE_HEADLIGHT_H
