// Generated by gencpp from file eve_msgs/HornResponse.msg
// DO NOT EDIT!


#ifndef EVE_MSGS_MESSAGE_HORNRESPONSE_H
#define EVE_MSGS_MESSAGE_HORNRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace eve_msgs
{
template <class ContainerAllocator>
struct HornResponse_
{
  typedef HornResponse_<ContainerAllocator> Type;

  HornResponse_()
    {
    }
  HornResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::eve_msgs::HornResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::eve_msgs::HornResponse_<ContainerAllocator> const> ConstPtr;

}; // struct HornResponse_

typedef ::eve_msgs::HornResponse_<std::allocator<void> > HornResponse;

typedef boost::shared_ptr< ::eve_msgs::HornResponse > HornResponsePtr;
typedef boost::shared_ptr< ::eve_msgs::HornResponse const> HornResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::eve_msgs::HornResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::eve_msgs::HornResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace eve_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::eve_msgs::HornResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::eve_msgs::HornResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eve_msgs::HornResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eve_msgs::HornResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eve_msgs::HornResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eve_msgs::HornResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::eve_msgs::HornResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::eve_msgs::HornResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::eve_msgs::HornResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eve_msgs/HornResponse";
  }

  static const char* value(const ::eve_msgs::HornResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::eve_msgs::HornResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::eve_msgs::HornResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::eve_msgs::HornResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HornResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::eve_msgs::HornResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::eve_msgs::HornResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // EVE_MSGS_MESSAGE_HORNRESPONSE_H
