// Generated by gencpp from file eve_msgs/HornRequest.msg
// DO NOT EDIT!


#ifndef EVE_MSGS_MESSAGE_HORNREQUEST_H
#define EVE_MSGS_MESSAGE_HORNREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace eve_msgs
{
template <class ContainerAllocator>
struct HornRequest_
{
  typedef HornRequest_<ContainerAllocator> Type;

  HornRequest_()
    : state(false)  {
    }
  HornRequest_(const ContainerAllocator& _alloc)
    : state(false)  {
  (void)_alloc;
    }



   typedef uint8_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::eve_msgs::HornRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::eve_msgs::HornRequest_<ContainerAllocator> const> ConstPtr;

}; // struct HornRequest_

typedef ::eve_msgs::HornRequest_<std::allocator<void> > HornRequest;

typedef boost::shared_ptr< ::eve_msgs::HornRequest > HornRequestPtr;
typedef boost::shared_ptr< ::eve_msgs::HornRequest const> HornRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::eve_msgs::HornRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::eve_msgs::HornRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::eve_msgs::HornRequest_<ContainerAllocator1> & lhs, const ::eve_msgs::HornRequest_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::eve_msgs::HornRequest_<ContainerAllocator1> & lhs, const ::eve_msgs::HornRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace eve_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::eve_msgs::HornRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::eve_msgs::HornRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eve_msgs::HornRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eve_msgs::HornRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eve_msgs::HornRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eve_msgs::HornRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::eve_msgs::HornRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "001fde3cab9e313a150416ff09c08ee4";
  }

  static const char* value(const ::eve_msgs::HornRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x001fde3cab9e313aULL;
  static const uint64_t static_value2 = 0x150416ff09c08ee4ULL;
};

template<class ContainerAllocator>
struct DataType< ::eve_msgs::HornRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eve_msgs/HornRequest";
  }

  static const char* value(const ::eve_msgs::HornRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::eve_msgs::HornRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool state\n"
;
  }

  static const char* value(const ::eve_msgs::HornRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::eve_msgs::HornRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HornRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::eve_msgs::HornRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::eve_msgs::HornRequest_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EVE_MSGS_MESSAGE_HORNREQUEST_H
