// Generated by gencpp from file eve_msgs/Horn.msg
// DO NOT EDIT!


#ifndef EVE_MSGS_MESSAGE_HORN_H
#define EVE_MSGS_MESSAGE_HORN_H

#include <ros/service_traits.h>


#include <eve_msgs/HornRequest.h>
#include <eve_msgs/HornResponse.h>


namespace eve_msgs
{

struct Horn
{

typedef HornRequest Request;
typedef HornResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Horn
} // namespace eve_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::eve_msgs::Horn > {
  static const char* value()
  {
    return "001fde3cab9e313a150416ff09c08ee4";
  }

  static const char* value(const ::eve_msgs::Horn&) { return value(); }
};

template<>
struct DataType< ::eve_msgs::Horn > {
  static const char* value()
  {
    return "eve_msgs/Horn";
  }

  static const char* value(const ::eve_msgs::Horn&) { return value(); }
};


// service_traits::MD5Sum< ::eve_msgs::HornRequest> should match
// service_traits::MD5Sum< ::eve_msgs::Horn >
template<>
struct MD5Sum< ::eve_msgs::HornRequest>
{
  static const char* value()
  {
    return MD5Sum< ::eve_msgs::Horn >::value();
  }
  static const char* value(const ::eve_msgs::HornRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::eve_msgs::HornRequest> should match
// service_traits::DataType< ::eve_msgs::Horn >
template<>
struct DataType< ::eve_msgs::HornRequest>
{
  static const char* value()
  {
    return DataType< ::eve_msgs::Horn >::value();
  }
  static const char* value(const ::eve_msgs::HornRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::eve_msgs::HornResponse> should match
// service_traits::MD5Sum< ::eve_msgs::Horn >
template<>
struct MD5Sum< ::eve_msgs::HornResponse>
{
  static const char* value()
  {
    return MD5Sum< ::eve_msgs::Horn >::value();
  }
  static const char* value(const ::eve_msgs::HornResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::eve_msgs::HornResponse> should match
// service_traits::DataType< ::eve_msgs::Horn >
template<>
struct DataType< ::eve_msgs::HornResponse>
{
  static const char* value()
  {
    return DataType< ::eve_msgs::Horn >::value();
  }
  static const char* value(const ::eve_msgs::HornResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EVE_MSGS_MESSAGE_HORN_H
