// Generated by gencpp from file eve_msgs/Status.msg
// DO NOT EDIT!


#ifndef EVE_MSGS_MESSAGE_STATUS_H
#define EVE_MSGS_MESSAGE_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace eve_msgs
{
template <class ContainerAllocator>
struct Status_
{
  typedef Status_<ContainerAllocator> Type;

  Status_()
    : header()
    , acceleration(0)
    , brake(0)
    , steering_angle(0)
    , driving_mode(0)
    , speed(0)
    , gear(0)
    , indicator(0)
    , headlight(0)
    , horn(false)
    , wiper(0)  {
    }
  Status_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , acceleration(0)
    , brake(0)
    , steering_angle(0)
    , driving_mode(0)
    , speed(0)
    , gear(0)
    , indicator(0)
    , headlight(0)
    , horn(false)
    , wiper(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _acceleration_type;
  _acceleration_type acceleration;

   typedef int8_t _brake_type;
  _brake_type brake;

   typedef int8_t _steering_angle_type;
  _steering_angle_type steering_angle;

   typedef uint8_t _driving_mode_type;
  _driving_mode_type driving_mode;

   typedef uint8_t _speed_type;
  _speed_type speed;

   typedef uint8_t _gear_type;
  _gear_type gear;

   typedef uint8_t _indicator_type;
  _indicator_type indicator;

   typedef uint8_t _headlight_type;
  _headlight_type headlight;

   typedef uint8_t _horn_type;
  _horn_type horn;

   typedef uint8_t _wiper_type;
  _wiper_type wiper;





  typedef boost::shared_ptr< ::eve_msgs::Status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::eve_msgs::Status_<ContainerAllocator> const> ConstPtr;

}; // struct Status_

typedef ::eve_msgs::Status_<std::allocator<void> > Status;

typedef boost::shared_ptr< ::eve_msgs::Status > StatusPtr;
typedef boost::shared_ptr< ::eve_msgs::Status const> StatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::eve_msgs::Status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::eve_msgs::Status_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::eve_msgs::Status_<ContainerAllocator1> & lhs, const ::eve_msgs::Status_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.acceleration == rhs.acceleration &&
    lhs.brake == rhs.brake &&
    lhs.steering_angle == rhs.steering_angle &&
    lhs.driving_mode == rhs.driving_mode &&
    lhs.speed == rhs.speed &&
    lhs.gear == rhs.gear &&
    lhs.indicator == rhs.indicator &&
    lhs.headlight == rhs.headlight &&
    lhs.horn == rhs.horn &&
    lhs.wiper == rhs.wiper;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::eve_msgs::Status_<ContainerAllocator1> & lhs, const ::eve_msgs::Status_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace eve_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::eve_msgs::Status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::eve_msgs::Status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eve_msgs::Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eve_msgs::Status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eve_msgs::Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eve_msgs::Status_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::eve_msgs::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2bd35173d866309f8624d2d2f6bcf3cb";
  }

  static const char* value(const ::eve_msgs::Status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2bd35173d866309fULL;
  static const uint64_t static_value2 = 0x8624d2d2f6bcf3cbULL;
};

template<class ContainerAllocator>
struct DataType< ::eve_msgs::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eve_msgs/Status";
  }

  static const char* value(const ::eve_msgs::Status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::eve_msgs::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"int8 acceleration\n"
"\n"
"int8 brake\n"
"\n"
"int8 steering_angle\n"
"\n"
"# Driving Mode\n"
"uint8 driving_mode\n"
"\n"
"# Speed\n"
"uint8 speed\n"
"\n"
"# Gear\n"
"uint8 gear\n"
"\n"
"# Indicator\n"
"uint8 indicator\n"
"\n"
"# Headlight\n"
"uint8 headlight\n"
"\n"
"# Horn\n"
"bool horn\n"
"\n"
"# Wiper\n"
"uint8 wiper\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::eve_msgs::Status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::eve_msgs::Status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.acceleration);
      stream.next(m.brake);
      stream.next(m.steering_angle);
      stream.next(m.driving_mode);
      stream.next(m.speed);
      stream.next(m.gear);
      stream.next(m.indicator);
      stream.next(m.headlight);
      stream.next(m.horn);
      stream.next(m.wiper);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::eve_msgs::Status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::eve_msgs::Status_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "acceleration: ";
    Printer<int8_t>::stream(s, indent + "  ", v.acceleration);
    s << indent << "brake: ";
    Printer<int8_t>::stream(s, indent + "  ", v.brake);
    s << indent << "steering_angle: ";
    Printer<int8_t>::stream(s, indent + "  ", v.steering_angle);
    s << indent << "driving_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.driving_mode);
    s << indent << "speed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.speed);
    s << indent << "gear: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gear);
    s << indent << "indicator: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.indicator);
    s << indent << "headlight: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.headlight);
    s << indent << "horn: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.horn);
    s << indent << "wiper: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.wiper);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EVE_MSGS_MESSAGE_STATUS_H
