// Generated by gencpp from file eve_msgs/Steering.msg
// DO NOT EDIT!


#ifndef EVE_MSGS_MESSAGE_STEERING_H
#define EVE_MSGS_MESSAGE_STEERING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace eve_msgs
{
template <class ContainerAllocator>
struct Steering_
{
  typedef Steering_<ContainerAllocator> Type;

  Steering_()
    : header()
    , steering_angle(0)
    , indicator(0)  {
    }
  Steering_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , steering_angle(0)
    , indicator(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _steering_angle_type;
  _steering_angle_type steering_angle;

   typedef uint8_t _indicator_type;
  _indicator_type indicator;





  typedef boost::shared_ptr< ::eve_msgs::Steering_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::eve_msgs::Steering_<ContainerAllocator> const> ConstPtr;

}; // struct Steering_

typedef ::eve_msgs::Steering_<std::allocator<void> > Steering;

typedef boost::shared_ptr< ::eve_msgs::Steering > SteeringPtr;
typedef boost::shared_ptr< ::eve_msgs::Steering const> SteeringConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::eve_msgs::Steering_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::eve_msgs::Steering_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::eve_msgs::Steering_<ContainerAllocator1> & lhs, const ::eve_msgs::Steering_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.steering_angle == rhs.steering_angle &&
    lhs.indicator == rhs.indicator;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::eve_msgs::Steering_<ContainerAllocator1> & lhs, const ::eve_msgs::Steering_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace eve_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::eve_msgs::Steering_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::eve_msgs::Steering_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eve_msgs::Steering_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eve_msgs::Steering_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eve_msgs::Steering_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eve_msgs::Steering_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::eve_msgs::Steering_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23a81283a703ac53f2cc24b4a11a4cf0";
  }

  static const char* value(const ::eve_msgs::Steering_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23a81283a703ac53ULL;
  static const uint64_t static_value2 = 0xf2cc24b4a11a4cf0ULL;
};

template<class ContainerAllocator>
struct DataType< ::eve_msgs::Steering_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eve_msgs/Steering";
  }

  static const char* value(const ::eve_msgs::Steering_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::eve_msgs::Steering_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"# Range -40 to +40, +40 is maximum left turn\n"
"int8 steering_angle\n"
"\n"
"# 0: Off, 1: Left, 2: Right\n"
"uint8 indicator\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::eve_msgs::Steering_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::eve_msgs::Steering_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.steering_angle);
      stream.next(m.indicator);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Steering_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::eve_msgs::Steering_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::eve_msgs::Steering_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "steering_angle: ";
    Printer<int8_t>::stream(s, indent + "  ", v.steering_angle);
    s << indent << "indicator: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.indicator);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EVE_MSGS_MESSAGE_STEERING_H
