// Generated by gencpp from file eve_msgs/Wiper.msg
// DO NOT EDIT!


#ifndef EVE_MSGS_MESSAGE_WIPER_H
#define EVE_MSGS_MESSAGE_WIPER_H

#include <ros/service_traits.h>


#include <eve_msgs/WiperRequest.h>
#include <eve_msgs/WiperResponse.h>


namespace eve_msgs
{

struct Wiper
{

typedef WiperRequest Request;
typedef WiperResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Wiper
} // namespace eve_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::eve_msgs::Wiper > {
  static const char* value()
  {
    return "800f34bc468def1d86e2d42bea5648c0";
  }

  static const char* value(const ::eve_msgs::Wiper&) { return value(); }
};

template<>
struct DataType< ::eve_msgs::Wiper > {
  static const char* value()
  {
    return "eve_msgs/Wiper";
  }

  static const char* value(const ::eve_msgs::Wiper&) { return value(); }
};


// service_traits::MD5Sum< ::eve_msgs::WiperRequest> should match
// service_traits::MD5Sum< ::eve_msgs::Wiper >
template<>
struct MD5Sum< ::eve_msgs::WiperRequest>
{
  static const char* value()
  {
    return MD5Sum< ::eve_msgs::Wiper >::value();
  }
  static const char* value(const ::eve_msgs::WiperRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::eve_msgs::WiperRequest> should match
// service_traits::DataType< ::eve_msgs::Wiper >
template<>
struct DataType< ::eve_msgs::WiperRequest>
{
  static const char* value()
  {
    return DataType< ::eve_msgs::Wiper >::value();
  }
  static const char* value(const ::eve_msgs::WiperRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::eve_msgs::WiperResponse> should match
// service_traits::MD5Sum< ::eve_msgs::Wiper >
template<>
struct MD5Sum< ::eve_msgs::WiperResponse>
{
  static const char* value()
  {
    return MD5Sum< ::eve_msgs::Wiper >::value();
  }
  static const char* value(const ::eve_msgs::WiperResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::eve_msgs::WiperResponse> should match
// service_traits::DataType< ::eve_msgs::Wiper >
template<>
struct DataType< ::eve_msgs::WiperResponse>
{
  static const char* value()
  {
    return DataType< ::eve_msgs::Wiper >::value();
  }
  static const char* value(const ::eve_msgs::WiperResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EVE_MSGS_MESSAGE_WIPER_H
